version: 2

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters:
  enable:
    - errcheck
    - staticcheck
    - unused
    - gosec
    - govet
    - ineffassign

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false
  gosec:
    excludes:
      - G104
    config:
      G306: "0600"
      G301: "0750"

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
